import { z } from 'zod';
import { id, isoDateTime, platformSchema, timestamps } from './common.js';
import type { DeviceActivationId, LicenseId, OrderId, ReleaseBuildId, UserId } from '../ids.js';

/**
 * Commerce, licensing and release delivery (spec §3, §12, §17).
 *
 * Entitlement is server-authoritative: a license exists only after Stripe
 * confirms payment server-side, and installer downloads are authorised against
 * the license rather than served from a permanently public URL.
 */

export const orderStatusSchema = z.enum(['pending', 'paid', 'refunded', 'failed', 'disputed']);
export type OrderStatus = z.infer<typeof orderStatusSchema>;

export const orderSchema = z.object({
  id: id<OrderId>(),
  userId: id<UserId>(),
  status: orderStatusSchema.default('pending'),
  /** Platform chosen at checkout — analytics/support only; see §3.2. */
  selectedPlatform: platformSchema.nullable().default(null),
  amountCents: z.number().int().nonnegative(),
  currency: z.string().length(3).default('usd'),
  /**
   * The checkout session id *is* the idempotency key (§17: a successful
   * purchase creates exactly one license even if the webhook is retried). It
   * is unique in the database, so a replayed webhook updates this order rather
   * than inserting a second one. There is deliberately no separate key: a
   * second identifier would be one more thing that could disagree.
   */
  stripeCheckoutSessionId: z.string().nullable().default(null),
  stripePaymentIntentId: z.string().nullable().default(null),
  stripeCustomerId: z.string().nullable().default(null),
  paidAt: isoDateTime().nullable().default(null),
  ...timestamps,
});
export type Order = z.infer<typeof orderSchema>;

export const licenseStatusSchema = z.enum(['active', 'suspended', 'revoked', 'expired']);
export type LicenseStatus = z.infer<typeof licenseStatusSchema>;

export const licenseSchema = z.object({
  id: id<LicenseId>(),
  userId: id<UserId>(),
  orderId: id<OrderId>(),
  /** Human-readable serial shown in the confirmation email (§12.3). */
  serial: z.string().min(1),
  status: licenseStatusSchema.default('active'),
  /**
   * Which installers this license may download. §18 keeps "one purchase grants
   * both OS installers" configurable, so this is data, not a hard-coded rule.
   */
  entitledPlatforms: z.array(platformSchema).min(1).default(['windows', 'macos']),
  maxActivations: z.number().int().positive().default(2),
  expiresAt: isoDateTime().nullable().default(null),
  ...timestamps,
});
export type License = z.infer<typeof licenseSchema>;

export const releaseChannelSchema = z.enum(['stable', 'beta', 'internal']);
export type ReleaseChannel = z.infer<typeof releaseChannelSchema>;

/**
 * §3.2/§17: Windows and macOS artifacts are published independently — shipping
 * a new Windows build must not replace the Mac artifact.
 */
export const releaseBuildSchema = z.object({
  id: id<ReleaseBuildId>(),
  platform: platformSchema,
  version: z.string().min(1),
  channel: releaseChannelSchema.default('stable'),
  minimumOsVersion: z.string().default(''),
  /** Storage key, never a public URL: downloads are signed on demand (§19). */
  artifactKey: z.string().min(1),
  artifactSizeBytes: z.number().int().nonnegative().default(0),
  sha256: z.string().default(''),
  releaseNotes: z.string().default(''),
  active: z.boolean().default(false),
  publishedAt: isoDateTime().nullable().default(null),
  ...timestamps,
});
export type ReleaseBuild = z.infer<typeof releaseBuildSchema>;

export const deviceActivationSchema = z.object({
  id: id<DeviceActivationId>(),
  licenseId: id<LicenseId>(),
  /** Stable per-install identifier generated by the desktop client. */
  deviceFingerprint: z.string().min(1),
  deviceName: z.string().default(''),
  platform: platformSchema,
  appVersion: z.string().default(''),
  activatedAt: isoDateTime(),
  lastSeenAt: isoDateTime().nullable().default(null),
  /** Deactivation is reversible bookkeeping, not a row delete (§3.3). */
  deactivatedAt: isoDateTime().nullable().default(null),
});
export type DeviceActivation = z.infer<typeof deviceActivationSchema>;

export const isActivationSlotAvailable = (license: License, activations: readonly DeviceActivation[]): boolean =>
  activations.filter((activation) => activation.deactivatedAt === null).length < license.maxActivations;

/**
 * Whether a licence is live **now** (addendum 32).
 *
 * It lives here beside the record's other predicates rather than in
 * `subscription.ts`, because every gate in the program asks it and a second
 * copy anywhere is a second answer to *is this person entitled*.
 *
 * Two things can end a licence and both are read: the status Stripe's last
 * word set, and the period it is paid up to. The second matters because a
 * webhook is a message that may not arrive — if Stripe's cancellation event is
 * lost the stored status still says active while the paid period has plainly
 * run out, and a date already in hand is a better answer than a message that
 * never came. **A licence with no expiry never lapses**, which is what every
 * row written before the subscription was.
 */
export const licenseLive = (license: Pick<License, 'status' | 'expiresAt'>, now: Date): boolean => {
  if (license.status !== 'active') return false;
  if (!license.expiresAt) return true;
  return new Date(license.expiresAt).getTime() > now.getTime();
};

export const canDownloadPlatform = (
  license: License,
  platform: z.infer<typeof platformSchema>,
  now: Date = new Date(),
): boolean => licenseLive(license, now) && license.entitledPlatforms.includes(platform);
