import { z } from 'zod';
import { id, isoDateTime, platformSchema, timestamps } from './common.js';
import type { DeviceActivationId, LicenseId, OrderId, ReleaseBuildId, UserId } from '../ids.js';

/**
 * Commerce, licensing and release delivery (spec §3, §12, §17).
 *
 * Entitlement is server-authoritative: a license exists only after Stripe
 * confirms payment server-side, and installer downloads are authorised against
 * the license rather than served from a permanently public URL.
 */

export const orderStatusSchema = z.enum(['pending', 'paid', 'refunded', 'failed', 'disputed']);
export type OrderStatus = z.infer<typeof orderStatusSchema>;

export const orderSchema = z.object({
  id: id<OrderId>(),
  userId: id<UserId>(),
  status: orderStatusSchema.default('pending'),
  /** Platform chosen at checkout — analytics/support only; see §3.2. */
  selectedPlatform: platformSchema.nullable().default(null),
  amountCents: z.number().int().nonnegative(),
  currency: z.string().length(3).default('usd'),
  stripeCheckoutSessionId: z.string().nullable().default(null),
  stripePaymentIntentId: z.string().nullable().default(null),
  stripeCustomerId: z.string().nullable().default(null),
  /**
   * Idempotency key for webhook replay (§17: a successful purchase creates
   * exactly one license even if the webhook is retried).
   */
  idempotencyKey: z.string().min(1),
  paidAt: isoDateTime().nullable().default(null),
  ...timestamps,
});
export type Order = z.infer<typeof orderSchema>;

export const licenseStatusSchema = z.enum(['active', 'suspended', 'revoked', 'expired']);
export type LicenseStatus = z.infer<typeof licenseStatusSchema>;

export const licenseSchema = z.object({
  id: id<LicenseId>(),
  userId: id<UserId>(),
  orderId: id<OrderId>(),
  /** Human-readable serial shown in the confirmation email (§12.3). */
  serial: z.string().min(1),
  status: licenseStatusSchema.default('active'),
  /**
   * Which installers this license may download. §18 keeps "one purchase grants
   * both OS installers" configurable, so this is data, not a hard-coded rule.
   */
  entitledPlatforms: z.array(platformSchema).min(1).default(['windows', 'macos']),
  maxActivations: z.number().int().positive().default(2),
  expiresAt: isoDateTime().nullable().default(null),
  ...timestamps,
});
export type License = z.infer<typeof licenseSchema>;

export const releaseChannelSchema = z.enum(['stable', 'beta', 'internal']);
export type ReleaseChannel = z.infer<typeof releaseChannelSchema>;

/**
 * §3.2/§17: Windows and macOS artifacts are published independently — shipping
 * a new Windows build must not replace the Mac artifact.
 */
export const releaseBuildSchema = z.object({
  id: id<ReleaseBuildId>(),
  platform: platformSchema,
  version: z.string().min(1),
  channel: releaseChannelSchema.default('stable'),
  minimumOsVersion: z.string().default(''),
  /** Storage key, never a public URL: downloads are signed on demand (§19). */
  artifactKey: z.string().min(1),
  artifactSizeBytes: z.number().int().nonnegative().default(0),
  sha256: z.string().default(''),
  releaseNotes: z.string().default(''),
  active: z.boolean().default(false),
  publishedAt: isoDateTime().nullable().default(null),
  ...timestamps,
});
export type ReleaseBuild = z.infer<typeof releaseBuildSchema>;

export const deviceActivationSchema = z.object({
  id: id<DeviceActivationId>(),
  licenseId: id<LicenseId>(),
  /** Stable per-install identifier generated by the desktop client. */
  deviceFingerprint: z.string().min(1),
  deviceName: z.string().default(''),
  platform: platformSchema,
  appVersion: z.string().default(''),
  activatedAt: isoDateTime(),
  lastSeenAt: isoDateTime().nullable().default(null),
  /** Deactivation is reversible bookkeeping, not a row delete (§3.3). */
  deactivatedAt: isoDateTime().nullable().default(null),
});
export type DeviceActivation = z.infer<typeof deviceActivationSchema>;

export const isActivationSlotAvailable = (license: License, activations: readonly DeviceActivation[]): boolean =>
  activations.filter((activation) => activation.deactivatedAt === null).length < license.maxActivations;

export const canDownloadPlatform = (license: License, platform: z.infer<typeof platformSchema>): boolean =>
  license.status === 'active' && license.entitledPlatforms.includes(platform);
